site_name: The teller
theme: slate

docs_dir: sources
repo_url: https://github.com/Techtonique/teller
edit_uri: ""
site_description: 'Documentation for the teller.'

nav:
    - Home: index.md
    - Documentation:
      - Comparator: documentation/comparator.md
      - Explainer: documentation/explainer.md