site_name: Techtonique/teller
theme:
  name: darkly # sandstone # slate # lux # darkly
  nav_style: dark
  #name: null
  #custom_dir: 'custom_theme/'

google_analytics: ['UA-146345113-2', 'https://techtonique.github.io/teller/']    

docs_dir: sources
repo_url: https://github.com/Techtonique/teller
edit_uri: ""
site_description: 'Documentation for the teller.'

nav:
    - Quickstart examples: quickstart.md
    - Documentation:
      - Comparator: documentation/comparator.md
      - Explainer: documentation/explainer.md
    - Contributing: CONTRIBUTING.md  
    - License: LICENSE.md  
    - Techtonique: ../  